const express = require("express")
const router = express.Router()
const dbController = require("../../controllers/dbController")
const router_redmine = require("./redmine/index.js")
router.get("/user/index", dbController.getAllUsers)
router.post("/user/update", dbController.update)
router.post("/user/delete", dbController.delete)
router.get("/role/index", dbController.getAllRoles)
router.get("/role/:id", dbController.getRole)
router.post("/role/create", dbController.createRole)
router.post("/role/update", dbController.updateRole)
router.post("/role/delete", dbController.deleteRole)
router.post("/role/request_role", dbController.requestRole)
router.route("/permission")
.get(dbController.getAllPermissions)
.post(dbController.createPermission)
.delete(dbController.deletePermission)
.patch(dbController.updatePermission)
router.post("/upload/images", dbController.uploadImages)
router.get("/issues/counter", dbController.getCounter)
router.use("/issues", router_redmine)
// router.route("/issues")
// .get(dbController.getIssues)
// .post(dbController.createIssue)
// .patch(dbController.updateIssue)
router.get("/issue/:id", dbController.getIssueIndex)

module.exports = router